name: Hello

env:
  owner: micbelgique
  repo: TestTriggerGHAction
on:
  repository_dispatch:
    types: [say-hello]

jobs:

  sayHello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
